M48
; DRILL file KiCad 10.0.4 date 2026-07-04T02:08:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-04T02:08:07+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X79.87Y-38.5
T2
X88.38Y-54.5
X143.62Y-38.5
M30
